import datetime
from mongoengine import Document, StringField, DictField, DateTimeField, ReferenceField, IntField
from apps.authentication.models import User

class JobCache(Document):
    """
    MongoEngine Job Cache Document.
    Caches job results queried via JSearch API.
    MongoDB TTL index automatically evicts documents on expires_at.
    """
    meta = {
        'collection': 'job_caches',
        'indexes': [
            'query',
            {'fields': ['expires_at'], 'expireAfterSeconds': 0}  # TTL Index
        ]
    }

    query = StringField(required=True, unique=True)
    payload = DictField(default=dict)
    created_at = DateTimeField(default=datetime.datetime.utcnow)
    expires_at = DateTimeField(required=True)


class CourseCache(Document):
    """
    MongoEngine Course Cache Document.
    Caches learning courses returned via YouTube Data API or other public learning sources.
    MongoDB TTL index automatically evicts documents on expires_at.
    """
    meta = {
        'collection': 'course_caches',
        'indexes': [
            'query',
            {'fields': ['expires_at'], 'expireAfterSeconds': 0}  # TTL Index
        ]
    }

    query = StringField(required=True, unique=True)
    payload = DictField(default=dict)
    created_at = DateTimeField(default=datetime.datetime.utcnow)
    expires_at = DateTimeField(required=True)


class SavedJob(Document):
    """
    Tracks jobs explicitly saved/bookmarked by the user.
    """
    meta = {
        'collection': 'saved_jobs',
        'indexes': [
            'user',
            '-created_at'
        ]
    }
    user = ReferenceField(User, required=True, reverse_delete_rule=2)
    job_id = StringField(required=True, unique_with='user')
    title = StringField(required=True)
    company = StringField(required=True)
    location = StringField(default='Remote')
    description = StringField(default='')
    url = StringField(default='')
    created_at = DateTimeField(default=datetime.datetime.utcnow)


class JobApplication(Document):
    """
    Tracks job applications and status steps for the user.
    """
    meta = {
        'collection': 'job_applications',
        'indexes': [
            'user',
            '-applied_at'
        ]
    }
    user = ReferenceField(User, required=True, reverse_delete_rule=2)
    job_id = StringField(required=True, unique_with='user')
    title = StringField(required=True)
    company = StringField(required=True)
    location = StringField(default='Remote')
    status = StringField(default='Applied', choices=['Applied', 'Interviewing', 'Offered', 'Rejected'])
    notes = StringField(default='')
    applied_at = DateTimeField(default=datetime.datetime.utcnow)
    updated_at = DateTimeField(default=datetime.datetime.utcnow)


class CareerInsightHistory(Document):
    """
    MongoEngine CareerInsightHistory Document.
    Tracks historical career insights generated by the user.
    """
    meta = {
        'collection': 'career_insights_history',
        'indexes': [
            'user',
            '-created_at'
        ]
    }

    user = ReferenceField(User, required=True, reverse_delete_rule=2)
    searched_role = StringField(max_length=255, required=True)
    generated_insight = DictField(default=dict)
    created_at = DateTimeField(default=datetime.datetime.utcnow)


class PlatformStatsCounter(Document):
    """
    MongoEngine PlatformStatsCounter Document.
    Tracks global lifetime platform statistics.
    """
    meta = {
        'collection': 'platform_stats_counters'
    }
    total_resume_uploads = IntField(default=0)
    total_ats_reports_generated = IntField(default=0)
    total_cover_letters_generated = IntField(default=0)
    total_interviews_completed = IntField(default=0)
    total_career_insights_generated = IntField(default=0)
    total_learning_roadmaps = IntField(default=0)

def ensure_platform_stats_initialized():
    try:
        if PlatformStatsCounter.objects.count() == 0:
            from apps.resumes.models import Resume, CoverLetter
            from apps.recommendations.models import CareerInsightHistory
            from apps.learning.models import Roadmap
            from apps.assessments.models import Scorecard
            
            resumes_count = Resume.objects.count()
            cover_letters_count = CoverLetter.objects.count()
            roadmaps_count = Roadmap.objects.count()
            career_insights_count = CareerInsightHistory.objects.count()
            scorecards_count = Scorecard.objects.count()
            ats_reports_count = resumes_count
            
            col = PlatformStatsCounter._get_collection()
            col.update_one(
                {},
                {"$setOnInsert": {
                    "total_resume_uploads": resumes_count,
                    "total_ats_reports_generated": ats_reports_count,
                    "total_cover_letters_generated": cover_letters_count,
                    "total_interviews_completed": scorecards_count,
                    "total_career_insights_generated": career_insights_count,
                    "total_learning_roadmaps": roadmaps_count
                }},
                upsert=True
            )
    except Exception as e:
        import logging
        logger = logging.getLogger("carvion.api")
        logger.error(f"Failed to initialize platform stats counter: {str(e)}")


def increment_lifetime_stat(stat_name):
    try:
        ensure_platform_stats_initialized()
        PlatformStatsCounter.objects.update_one(upsert=True, **{f"inc__{stat_name}": 1})
    except Exception as e:
        import logging
        logger = logging.getLogger("carvion.api")
        logger.error(f"Failed to increment lifetime stat {stat_name}: {str(e)}")


class SavedCourse(Document):
    """
    Tracks courses explicitly saved/bookmarked by the user.
    """
    meta = {
        'collection': 'saved_courses',
        'indexes': [
            'user',
            '-created_at'
        ]
    }
    user = ReferenceField(User, required=True, reverse_delete_rule=2)
    course_id = StringField(required=True, unique_with='user')
    title = StringField(required=True)
    provider = StringField(default='')
    description = StringField(default='')
    thumbnail = StringField(default='')
    url = StringField(default='')
    created_at = DateTimeField(default=datetime.datetime.utcnow)


class AICache(Document):
    """
    General AI/API cache document.
    """
    meta = {
        'collection': 'ai_caches',
        'indexes': [
            'key',
            'user',
            {'fields': ['expires_at'], 'expireAfterSeconds': 0}
        ]
    }
    user = ReferenceField(User, required=False, reverse_delete_rule=2)
    key = StringField(required=True, unique=True)
    payload = DictField(default=dict)
    created_at = DateTimeField(default=datetime.datetime.utcnow)
    expires_at = DateTimeField(required=True)
    version_hash = StringField(default="")



