import datetime
from mongoengine import Document, ReferenceField, StringField, ListField, DictField, DateTimeField, BooleanField, IntField, FloatField
from apps.authentication.models import User

class Roadmap(Document):
    """
    MongoEngine Learning Roadmap Document.
    Tracks user target career paths, milestones generated by Gemini,
    and individual node completion statuses.
    """
    meta = {
        'collection': 'roadmaps',
        'indexes': [
            'user',
            '-created_at'
        ]
    }

    user = ReferenceField(User, required=True, reverse_delete_rule=2)  # CASCADE
    target_role = StringField(required=True, max_length=255)
    
    # Milestones holds a list of structured node dictionaries:
    # {
    #   "id": "node_1",
    #   "title": "Learn Git & Version Control",
    #   "description": "...",
    #   "timeframe": "Week 1",
    #   "skills": ["Git", "GitHub"],
    #   "references": ["Link to course"],
    #   "is_completed": false
    # }
    milestones = ListField(DictField(), default=list)
    is_active = BooleanField(default=False)
    is_system_generated = BooleanField(default=False)
    profile_state_hash = StringField(default="")
    schema_version = IntField(default=1)
    
    created_at = DateTimeField(default=datetime.datetime.utcnow)
    updated_at = DateTimeField(default=datetime.datetime.utcnow)


class LearningActivity(Document):
    """
    Tracks individual learning activity per user per day.
    Used for analytics: daily/weekly/monthly graphs, streaks, hours watched.
    Each record is upserted once per day per user.
    """
    meta = {
        'collection': 'learning_activities',
        'indexes': [
            'user',
            '-date',
            ('user', 'date')
        ]
    }

    user = ReferenceField(User, required=True, reverse_delete_rule=2)
    date = StringField(required=True)  # ISO date string: "2026-06-26"
    minutes_studied = IntField(default=0)
    videos_watched = IntField(default=0)
    courses_completed = IntField(default=0)
    milestones_completed = IntField(default=0)
    created_at = DateTimeField(default=datetime.datetime.utcnow)
    updated_at = DateTimeField(default=datetime.datetime.utcnow)


class LearningSession(Document):
    """
    Tracks individual learning sessions per user.
    """
    meta = {
        'collection': 'learning_sessions',
        'indexes': [
            'user',
            '-start_time',
            'activity_type',
            'course_id',
            'date'
        ]
    }
    user = ReferenceField(User, required=True, reverse_delete_rule=2)
    activity_type = StringField(required=True, choices=['Video', 'Roadmap', 'Reading', 'Practice'])
    start_time = DateTimeField(required=True)
    end_time = DateTimeField(required=True)
    duration = IntField(default=0)  # in seconds
    course_id = StringField(null=True)
    course_title = StringField(default='')
    video_id = StringField(null=True)
    completion_percentage = IntField(default=0)
    roadmap_id = StringField(null=True)
    date = StringField(required=True)  # YYYY-MM-DD
    created_at = DateTimeField(default=datetime.datetime.utcnow)
    updated_at = DateTimeField(default=datetime.datetime.utcnow)


class WatchedCourse(Document):
    """
    Tracks course videos watched by the user to prevent double counting.
    """
    meta = {
        'collection': 'watched_courses',
        'indexes': [
            'user',
            ('user', 'course_id')
        ]
    }
    user = ReferenceField(User, required=True, reverse_delete_rule=2)
    course_id = StringField(required=True)
    title = StringField(default='')
    url = StringField(default='')
    created_at = DateTimeField(default=datetime.datetime.utcnow)


class RoadmapVideoProgress(Document):
    """
    Tracks watch progress for learning videos associated with career roadmap milestones.
    """
    meta = {
        'collection': 'roadmap_video_progress',
        'indexes': [
            'user',
            'roadmap',
            ('user', 'roadmap', 'milestone_id', 'video_id')
        ]
    }
    user = ReferenceField(User, required=True, reverse_delete_rule=2)
    roadmap = ReferenceField(Roadmap, required=True, reverse_delete_rule=2)
    milestone_id = StringField(required=True)
    video_id = StringField(required=True)
    title = StringField(default='')
    thumbnail = StringField(default='')
    channel = StringField(default='')
    duration = IntField(default=0)  # in seconds
    
    watch_start_time = DateTimeField(default=datetime.datetime.utcnow)
    watch_end_time = DateTimeField(default=datetime.datetime.utcnow)
    last_position = IntField(default=0)  # in seconds
    percentage_watched = IntField(default=0)  # 0 to 100
    total_minutes_watched = FloatField(default=0.0)
    completed = BooleanField(default=False)
    completion_date = DateTimeField(null=True)
    
    created_at = DateTimeField(default=datetime.datetime.utcnow)
    updated_at = DateTimeField(default=datetime.datetime.utcnow)
