import datetime
from mongoengine import Document, ReferenceField, StringField, ListField, DictField, IntField, DateTimeField
from apps.authentication.models import User

class MockTest(Document):
    """
    MongoEngine Mock Test Document.
    Stores test sessions generated by Gemini (domain topic, difficulty, questions list).
    """
    meta = {
        'collection': 'mock_tests',
        'indexes': [
            'user',
            '-created_at'
        ]
    }

    user = ReferenceField(User, required=True, reverse_delete_rule=2)
    domain = StringField(required=True, max_length=100)
    difficulty = StringField(required=True, choices=['Easy', 'Medium', 'Hard'])
    category = StringField(required=True, choices=['MCQ', 'Technical', 'Coding', 'Aptitude', 'HR'])
    
    # List of question objects:
    # {
    #   "id": 1,
    #   "question": "What is state in React?",
    #   "options": ["Opt A", "Opt B", "Opt C", "Opt D"],
    #   "correct_answer": 0, (index of correct option)
    #   "rationale": "Explanation..."
    # }
    questions = ListField(DictField(), default=list)
    created_at = DateTimeField(default=datetime.datetime.utcnow)


class Scorecard(Document):
    """
    MongoEngine Scorecard Document.
    Chronologically tracks test performance results and saves user analytics scorecards.
    """
    meta = {
        'collection': 'scorecards',
        'indexes': [
            'user',
            '-created_at'
        ]
    }

    user = ReferenceField(User, required=True, reverse_delete_rule=2)
    mock_test = ReferenceField(MockTest, null=True, reverse_delete_rule=2)
    
    domain = StringField(required=True, max_length=100)
    difficulty = StringField(required=True)
    category = StringField(required=True)
    
    score = IntField(default=0)  # Percentage score (e.g. 80 for 80%)
    total_questions = IntField(required=True)
    correct_answers = IntField(required=True)
    duration = IntField(default=0) # time taken in seconds
    performance_review = DictField(default=dict)
    
    # Mapping of user answers: [{"question_id": 1, "selected_option": 2, "is_correct": true}]
    answers_submitted = ListField(DictField(), default=list)
    
    created_at = DateTimeField(default=datetime.datetime.utcnow)


class InterviewSession(Document):
    """
    MongoEngine InterviewSession Document.
    Tracks real-time adaptive text and voice mock interview dialogues and their evaluations.
    """
    meta = {
        'collection': 'interview_sessions',
        'indexes': [
            'user',
            '-created_at'
        ]
    }

    user = ReferenceField(User, required=True, reverse_delete_rule=2)
    role = StringField(required=True, max_length=255)
    mode = StringField(default="text", choices=["text", "voice"])
    status = StringField(default="in_progress", choices=["in_progress", "completed"])
    difficulty = StringField(default="Medium")
    category = StringField(default="Technical")
    
    # Store questions and answers dialog: [{"question": "...", "answer": "...", "confidence": "...", "accuracy": "...", "timestamp": "..."}]
    dialog = ListField(DictField(), default=list)
    
    # Final AI Evaluation
    evaluation = DictField(default=dict)
    
    created_at = DateTimeField(default=datetime.datetime.utcnow)

