import datetime
from mongoengine import Document, ReferenceField, StringField, DictField, IntField, DateTimeField, BooleanField, ListField
from apps.authentication.models import User
from common.soft_delete_base import SoftDeleteDocument

class Resume(SoftDeleteDocument):
    """
    MongoEngine Resume Document.
    Tracks resume texts parsed via PyMuPDF/docx, structured parameters from the builder workspace,
    historical ATS scoring audits, and Gemini evaluations.
    """
    meta = {
        'collection': 'resumes',
        'indexes': [
            'user',
            '-created_at'
        ]
    }

    user = ReferenceField(User, required=True, reverse_delete_rule=2)  # CASCADE
    name = StringField(required=True, max_length=255)                  # Friendly identifier
    file_name = StringField(max_length=255, null=True)                 # Original file name if uploaded
    file_path = StringField(null=True)                                 # Path to saved original file
    extracted_text = StringField(default="")
    
    # Structured data holds builder form fields: Experience, Education, Projects, Skills, Certifications, etc.
    structured_data = DictField(default=dict)
    
    ats_score = IntField(default=0)
    
    # Analysis report stores Gemini JSON audit details: missing keywords, style/structural critiques, advice.
    analysis_report = DictField(default=dict)
    
    downloads_count = IntField(default=0)
    is_primary = BooleanField(default=False)
    
    created_at = DateTimeField(default=datetime.datetime.utcnow)
    updated_at = DateTimeField(default=datetime.datetime.utcnow)


class ResumeOptimization(SoftDeleteDocument):
    """
    MongoEngine ResumeOptimization Document.
    Tracks historical resume optimizations requested by the user.
    """
    meta = {
        'collection': 'resume_optimizations',
        'indexes': [
            'user',
            '-created_at'
        ]
    }

    user = ReferenceField(User, required=True, reverse_delete_rule=2)
    resume = ReferenceField(Resume, required=False, reverse_delete_rule=2)
    target_role = StringField(max_length=255)
    optimized_text = StringField(default="")
    
    ats_improvements = ListField(StringField(), default=list)
    formatting_suggestions = ListField(StringField(), default=list)
    grammar_improvements = ListField(StringField(), default=list)
    skill_recommendations = ListField(StringField(), default=list)
    missing_keywords = ListField(StringField(), default=list)
    action_verb_suggestions = ListField(StringField(), default=list)
    industry_recommendations = ListField(StringField(), default=list)
    is_fallback = BooleanField(default=False)
    
    created_at = DateTimeField(default=datetime.datetime.utcnow)


class CoverLetter(SoftDeleteDocument):
    """
    MongoEngine CoverLetter Document.
    Tracks historical cover letters generated by the user.
    """
    meta = {
        'collection': 'cover_letters',
        'indexes': [
            'user',
            '-created_at'
        ]
    }

    user = ReferenceField(User, required=True, reverse_delete_rule=2)
    resume = ReferenceField(Resume, required=False, reverse_delete_rule=2)
    target_role = StringField(max_length=255)
    company_name = StringField(max_length=255)
    job_description = StringField(default="")
    cover_letter_text = StringField(default="")
    is_fallback = BooleanField(default=False)
    
    created_at = DateTimeField(default=datetime.datetime.utcnow)

